# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Catergorie',
        ),
    ]
