# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 21:02
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0004_size_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=0, max_length=18, null=True),
        ),
    ]
