# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 21:17
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_auto_20190409_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('XXXS', 'XXXSmall'), ('XXS', 'XXSmall'), ('XS', 'XSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge'), ('XXXL', 'XXXLarge'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('12', '12')], default=0, max_length=63, null=True),
        ),
    ]
