# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0006_auto_20190403_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='men',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='unisex',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='women',
            name='parent_category',
        ),
    ]
