# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ('-user',), 'verbose_name_plural': 'Profiles'},
        ),
    ]
