# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileslineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilesLineItem',
        ),
        migrations.AddField(
            model_name='profiles',
            name='country',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profiles',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='street_address1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profiles',
            name='street_address2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profiles',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
