# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_auto_20190321_0049'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catergories',
            field=models.ManyToManyField(to='catergories.Men'),
        ),
    ]
