# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_catergories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catergories',
        ),
        migrations.AddField(
            model_name='product',
            name='catergories',
            field=models.CharField(choices=[(0, '------'), (1, 'Mens'), (2, 'Womens'), (3, 'Unisexs'), (4, 'Extra')], default=1, max_length=8),
        ),
    ]
