# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190331_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(default='------', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergories',
            field=models.CharField(choices=[('------', '------'), ('Mens', 'Mens'), ('Womens', 'Womens'), ('Unisexs', 'Unisexs'), ('Extra', 'Extra')], default='------', max_length=8),
        ),
    ]
