# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_auto_20190321_0049'),
        ('products', '0004_auto_20190331_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(to='catergories.Men'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergories',
            field=models.CharField(blank=True, choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Unisexs', 'Unisexs'), ('Extra', 'Extra')], default=1, max_length=8),
        ),
    ]
