# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190401_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergories',
            field=models.CharField(blank=True, choices=[('Men', 'Mens'), ('Women', 'Womens'), ('Unisex', 'Unisexs'), ('Extra', 'Extras')], default=1, max_length=8),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sections',
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.CharField(blank=True, choices=[('Men', 'Mens'), ('Women', 'Womens'), ('Unisex', 'Unisexs'), ('Extra', 'Extras')], default=1, max_length=8),
        ),
    ]
