# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190401_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(to='catergories.Extra'),
        ),
    ]
