# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_auto_20190321_0049'),
        ('products', '0008_auto_20190401_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sections',
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catergories.Men'),
        ),
    ]
