# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0005_auto_20190321_0049'),
        ('products', '0011_product_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sections',
            new_name='Mens',
        ),
        migrations.AddField(
            model_name='product',
            name='Extras',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catergories.Extra'),
        ),
        migrations.AddField(
            model_name='product',
            name='Unisexs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catergories.Unisex'),
        ),
        migrations.AddField(
            model_name='product',
            name='Womens',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catergories.Women'),
        ),
    ]
