# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190401_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Extras',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Mens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Unisexs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Womens',
        ),
        migrations.AddField(
            model_name='product',
            name='catergories',
            field=models.CharField(blank=True, choices=[('Men', 'Mens'), ('Women', 'Womens'), ('Unisex', 'Unisexs'), ('Extra', 'Extra')], default=0, max_length=8),
        ),
    ]
