# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190401_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergories', models.CharField(blank=True, choices=[('Men', 'Mens'), ('Women', 'Womens'), ('Unisex', 'Unisexs'), ('Extra', 'Extra')], default=0, max_length=8)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Catergory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='catergories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Catergory'),
        ),
    ]
