# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190403_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catergory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catergories',
        ),
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.CharField(blank=True, choices=[('Men', 'Mens'), ('Women', 'Womens'), ('Unisex', 'Unisexs'), ('Extra', 'Extras')], default=0, max_length=8),
        ),
        migrations.DeleteModel(
            name='Catergory',
        ),
    ]
